### ISSUE TITLE
Template Review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [marketingmakers/sklikgtmtemplate#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needs to be resolved ahead of approving the template for the gallery.

1) User instructions to install the template should direct users to install the gallery version of the template by clicking on the "Search Gallery" button in the template tab to add the gallery template.

**Comment by marketingmakers** [comment]
Hello, I have updated install instruction. This was just temporary settings as I have many people who are using it and testing it now, so this was tutorial for them. There was a plan to update it as soon as template is published. 

I apologise for Czech language used everywhere. I have added some English descriptions to make it better for you and Google template gallery. This system is only used in our country so there was no need for fully English solution.

**Comment by marketingmakers** [comment]
Hello, could you please let me know why this template disappeared from the listing? I can see it here https://tagmanager.google.com/gallery/#/owners/marketingmakers/templates/sklikgtmtemplate but I cannot add it to any workspace. It is not available in gallery. Thank you
