### ISSUE TITLE
Konverzní kód pro zbozi.cz uź asi nefunguje?

### ISSUE THREAD

**Issue by robkecz** [marketingmakers/sklikgtmtemplate#2]
Dobrý den,
podle téhle dokumentace https://github.com/seznam/zbozi-konverze se musí společně s objednávkou odeslat i informace o objednaném zboží, atd. Tohle asi tento script nepodporuje? Musí se tedy implementovat přímo v kódu stránky? Nelze provést také pomocí GTM rozšířením této šablony?
Díky za info.

**Comment by marketingmakers** [comment]
Dobrý den, to co zmiňujete bude back-endová část konverzního kódu. My v rámci GTM řešíme jenom tu front-endovou, která funguje, minimálně u našich projektů. Přidání produktů, tedy té back-endové části není možné přes Tag Manager udělat. Většinou to v sobě už ale mají všechny české krabicové systémy pro e-shopy.
